os:
  - linux
dist: trusty

language: node_js
node_js:
  - '13.0'

addons:
  chrome: stable

cache:
  directories:
  - "./node_modules"

install:
- npm install

script:
- npm run test -- --watch=false --no-progress --browsers=ChromeHeadless

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - "./send.sh success $WEBHOOK_URL"

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - "./send.sh failure $WEBHOOK_URL"

before-deploy:
- npm run build

deploy:
  provider: heroku
  api_key:
    secure: DYhbU2ycG8AFndee57NDhIrSCx69LYZsPkwrhOvuvzJc1FXW0JpBCBWc2xcfImmKb8BiipAMjkAoDEN6cNu5OOzhaIE9ywicQF6bg9G6YM3DnMBSUDlt1xqodl4xN+91aN7oFZJQBChRZwt16m2PBsT+UPAxn83X6ahN+ssXvOpesyistLtFYmxnTqr/hHWqWrIkw3ko+DVB/EfWBITrm0mxNTMqBZUEru5O0Qm14s7aRwH1g0qrKMFHdRWtWUb58N13+aQBovZ5eHkhJ8gADXs7gFDGLrMNAw75S2UkbqX5OKtB8KxcB/2xGiJqwjsyQewOv6YAdSDC5NkX53hzSGHHOKxbPRES+po+q+TRqnxMnDFYoqI+/S5TJxgPzS44CljEKPUCEhhZf9wyqCRjSo6zAvGgJ3aN7maFYSJqwfaNzIMnYNc1FAy9IZEpwlsqzJCthXSzhToKEuzdsO5p+tL6T75hpcc99A3ff2ug1qHAszgfJBGJXUY1cDGFC8/IiOzaPxj/lLkZKD8tFwshsj+8+J1J4ZxKWztPqLYlzx4/cNN6oS+ezkE/iFrhQysOytsS4g7JbEitNNtDMlrrNsN33n/IL0DNvGch7ISPCU7WobFx/hKYDqHc4Z/EnZKWC6HxFBWVCObFfiKRT8z2rouOKH4l8B2T6ZaALYBePVk=
  app: leafer-app
  on: release
  skip_cleanup: true

notifications:
  email: false
